[package]
name = "chain"
version = "0.5.0"
edition = "2021"

[features]
simulation-mode = []

[dependencies]
alloy-primitives = "0.8.15"
alloy-sol-types = "0.8.15"
anyhow = "1.0"
bincode = "1.3.3"
hyperware_process_lib = "1.0.3"
process_macros = "0.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
sha3 = "0.10.8"
url = "2.4.1"
urlencoding = "2.1.0"
wit-bindgen = "0.36.0"
zip = { version = "1.1.1", default-features = false }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "hyperware:process"
